# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/mydb
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"
    command: npm run start:env
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:11.5
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb

volumes:
  db-data:
    driver: local
